---
#version: '3'
#services:
#  db:
#    image: postgres_db    
#    ports:
#      - "5432:5432"
#    volumes:
#      - /volumes/srv/docker/postgresql:/var/lib/postgresql
  flyway:
    build: flyway_postgres/
    environment:
      FLYWAY_URL: "jdbc:postgresql://172.17.0.2:5432/bliss"
      FLYWAY_DRIVER: "org.postgresql.Driver"
      FLYWAY_EDITION: "community"
      FLYWAY_BASELINE_ON_MIGRATE: "true"
      FLYWAY_BASELINE_VERSION: "0"
      FLYWAY_COMMAND: "info"
      FLYWAY_ENVIORNMENT: "UAT"
    #  FLYWAY_OUT_OF_ORDER: "true"
    #volumes:
    #  - ./flyway-migrations:/flyway/sql      
    #depends_on:
     # - db  

#volumes:
 # printdata:
